export const mockPosts = [
  {
    id: 1,
    author: "Priya Sharma",
    role: "VP Product @ TechCorp",
    avatar: "PS",
    content: "Excited to announce our Q3 product roadmap — AI-first workflows, real-time collaboration, and a redesigned onboarding experience. The future is here. 🚀",
    likes: 1432,
    comments: 87,
    shares: 204,
    time: "2h ago",
    intent: "Brand Awareness",
    industry: "SaaS / Product",
    sentiment: "Positive",
    relevance: 94,
    tags: ["Product Launch", "AI", "Leadership"],
  },
  {
    id: 2,
    author: "Rahul Mehta",
    role: "Founder @ GrowthLab",
    avatar: "RM",
    content: "Most B2B companies spend 80% of their budget on acquisition and almost nothing on retention. The math never works. Here's how we flipped it...",
    likes: 3201,
    comments: 312,
    shares: 891,
    time: "5h ago",
    intent: "Thought Leadership",
    industry: "Marketing / Growth",
    sentiment: "Neutral",
    relevance: 88,
    tags: ["B2B", "Growth", "Retention"],
  },
  {
    id: 3,
    author: "Ananya Iyer",
    role: "Head of Sales @ CloudBase",
    avatar: "AI",
    content: "Just closed our biggest enterprise deal of the year — $2.4M ARR. The secret? Listening more than pitching. A genuine 'what keeps you up at night?' goes further than any deck.",
    likes: 5842,
    comments: 463,
    shares: 1102,
    time: "1d ago",
    intent: "Purchase Intent",
    industry: "Enterprise Sales",
    sentiment: "Positive",
    relevance: 97,
    tags: ["Sales", "Enterprise", "ARR"],
  },
  {
    id: 4,
    author: "Kiran Nair",
    role: "CTO @ DevOps.io",
    avatar: "KN",
    content: "We migrated 200+ microservices to Kubernetes in 6 months with zero downtime. Here's our full migration playbook — free to use for your team.",
    likes: 7103,
    comments: 589,
    shares: 2341,
    time: "2d ago",
    intent: "Educational",
    industry: "DevOps / Cloud",
    sentiment: "Positive",
    relevance: 76,
    tags: ["Kubernetes", "DevOps", "Cloud"],
  },
  {
    id: 5,
    author: "Meera Pillai",
    role: "HR Director @ PeopleFirst",
    avatar: "MP",
    content: "We're hiring 50+ engineers across Bangalore and Hyderabad. Remote-first culture, competitive equity, and a real work-life balance policy. DM me directly.",
    likes: 892,
    comments: 241,
    shares: 88,
    time: "3d ago",
    intent: "Recruitment",
    industry: "Human Resources",
    sentiment: "Positive",
    relevance: 62,
    tags: ["Hiring", "Engineering", "Remote"],
  },
];

export const mockProfiles = [
  { id: 1, name: "Priya Sharma", role: "VP Product", company: "TechCorp", connections: "500+", score: 94, status: "Hot Lead", industry: "SaaS" },
  { id: 2, name: "Rahul Mehta", role: "Founder", company: "GrowthLab", connections: "500+", score: 88, status: "Warm Lead", industry: "Marketing" },
  { id: 3, name: "Ananya Iyer", role: "Head of Sales", company: "CloudBase", connections: "500+", score: 97, status: "Hot Lead", industry: "Enterprise" },
  { id: 4, name: "Kiran Nair", role: "CTO", company: "DevOps.io", connections: "500+", score: 76, status: "Prospect", industry: "DevOps" },
  { id: 5, name: "Meera Pillai", role: "HR Director", company: "PeopleFirst", connections: "200+", score: 62, status: "Prospect", industry: "HR" },
];

export const engagementData = [
  { day: "Mon", posts: 12, leads: 4, engagements: 230 },
  { day: "Tue", posts: 18, leads: 7, engagements: 380 },
  { day: "Wed", posts: 9, leads: 3, engagements: 190 },
  { day: "Thu", posts: 24, leads: 11, engagements: 510 },
  { day: "Fri", posts: 31, leads: 14, engagements: 670 },
  { day: "Sat", posts: 8, leads: 2, engagements: 140 },
  { day: "Sun", posts: 6, leads: 1, engagements: 95 },
];

export const intentDistribution = [
  { name: "Thought Leadership", value: 34, color: "#0077B5" },
  { name: "Purchase Intent", value: 22, color: "#00A0DC" },
  { name: "Brand Awareness", value: 19, color: "#313335" },
  { name: "Recruitment", value: 14, color: "#86888A" },
  { name: "Educational", value: 11, color: "#C5CCD6" },
];

export const industryData = [
  { industry: "SaaS", posts: 142, leads: 38 },
  { industry: "Marketing", posts: 98, leads: 24 },
  { industry: "Enterprise", posts: 76, leads: 31 },
  { industry: "DevOps", posts: 54, leads: 12 },
  { industry: "FinTech", posts: 41, leads: 9 },
];
